### PR TITLE
BLD: Add missing run_export

### PR DESCRIPTION
**Pull request by carterbox**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Please add an appropriate run_export to your package which pins an ABI compatible version of this package downstream.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@conda-forge-admin, please rerender

**Comment by kmuehlbauer** [comment]
@carterbox Is the pin down to micro-level necessary? I've no knowledge on that terrain. @hobu Do you know how ABI compatibility is with shapelib major, minor, micro?

We would need to bump the build number, to upload new packages for the current version.

**Comment by hobu** [comment]
> @hobu Do you know how ABI compatibility is with shapelib major, minor, micro?

micro is probably too aggressive. Shapelib evolves at geologic pace.

**Comment by carterbox** [comment]
> Is the pin down to micro-level necessary? 

This is a question for you as feedstock maintainers to answer. I just opened this PR to get y'all started because I noticed the run_export was missing when reviewing a new package on staged-recipes. Please edit this PR directly to change the pinning as you see fit.

**Comment by kmuehlbauer** [comment]
To maintain at least some consistency through the stack, what pinning for shapelib would you recommend here, @rouault?

**Comment by rouault** [comment]
> To maintain at least some consistency through the stack, what pinning for shapelib would you recommend here, @rouault?

Probably minor would be fine. I'm not sure we have released in recent times a micro != 0

**Comment by kmuehlbauer** [comment]
@conda-forge-admin, please rerender

**Review by kmuehlbauer — APPROVED** [review]

**Comment by carterbox** [comment]
Thanks!

**Pull request merged**
